"""Retired-file planning against real Git, isolated profiles and transactions."""
import contextlib
import importlib.util
import io
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
MODULE = ROOT / 'runtime/updater/legacy.py'
sys.path.insert(0, str(MODULE.parent))
from transaction import Transaction, plain, read, rollback

# Exact original 2140331^:runtime/hooks/user-prompt.ps1, not generated by legacy.py.
PROMPT = b"""try {
    $payload = @{ hookSpecificOutput = @{ hookEventName = 'UserPromptSubmit'; additionalContext = '[Conductor active] Step 0 before responding; gates and counters in force; state lives in the conductor todo entry.' } } | ConvertTo-Json -Depth 3 -Compress
    [Console]::Out.Write($payload)
    exit 0
} catch {
    exit 0
}
"""
# Exact original 6f1d543^:runtime/git-hooks/post-merge.
POST_MERGE = b'''#!/bin/sh
# conductor gate: merge consumer (this line is the sentinel installers/detectors grep).
# Consumes the single-use verification marker after a successful MERGE - git runs
# post-merge here, NOT post-commit (measured: a gated --no-ff merge left the marker
# untouched until this hook existed). Fast-forward merges also land here: consuming the
# marker for them is the strict direction - may force a re-prove, never a false allow.
MARKER=$(git rev-parse --path-format=absolute --git-path conductor-verified 2>/dev/null) ||
    MARKER="$(git rev-parse --absolute-git-dir 2>/dev/null)/conductor-verified"
case "$MARKER" in
    /conductor-verified) exit 0 ;;
esac
[ -f "$MARKER" ] && rm -f "$MARKER"

CHAINED=$(git rev-parse --path-format=absolute --git-path hooks/post-merge.pre-conductor 2>/dev/null)
if [ -n "$CHAINED" ] && [ -f "$CHAINED" ]; then
    if [ -x "$CHAINED" ]; then
        "$CHAINED" "$@"
    else
        sh "$CHAINED" "$@"
    fi
fi
exit 0
'''


class LocalPaths:
    """Independent target contract while main integrates the real Paths mapping."""
    def __init__(self, root):
        self.profile = plain(root / 'profile Ж & space')
        self.config = self.profile / '.claude'
        self.runtime = self.config / 'conductor'
        self.backups = self.profile / '.local/state/conductor/updates'
        self.runtime.mkdir(parents=True)

    def target(self, key):
        if key == 'gitconfig':
            return plain(self.profile / '.gitconfig')
        if key == 'gitconfig-xdg':
            return plain(self.profile / '.config/git/config')
        if key.startswith('legacy/'):
            return plain(self.runtime / key.removeprefix('legacy/'))
        raise ValueError('unexpected test target: ' + key)


class Plan(dict):
    def __init__(self):
        super().__init__()
        self.expected = {}


class LegacyTests(unittest.TestCase):
    def setUp(self):
        self.assertTrue(MODULE.is_file(), 'legacy cleanup implementation is absent')
        spec = importlib.util.spec_from_file_location('legacy_under_test', MODULE)
        self.module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.module)
        temporary = tempfile.TemporaryDirectory(prefix='conductor-legacy-')
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.paths = LocalPaths(self.root)
        env = {k: v for k, v in os.environ.items() if not k.upper().startswith('GIT_')}
        env.update(HOME=str(self.paths.profile), USERPROFILE=str(self.paths.profile),
                   XDG_CONFIG_HOME=str(self.paths.profile / '.config'), GIT_CONFIG_NOSYSTEM='1')
        self.environ = patch.dict(os.environ, env, clear=True)
        self.environ.start()
        self.addCleanup(self.environ.stop)
        self.plan = Plan()

    def put(self, relative, data, mode=0o644):
        path = self.paths.runtime / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        path.chmod(mode)
        return path

    def config(self, key='gitconfig', value=None):
        path = self.paths.target(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b'# personal comment\n[user]\n\tname = Private Name\n')
        target = str(self.paths.runtime / 'git-template') if value is None else value
        subprocess.run(['git', 'config', '--file', str(path), 'init.templateDir', target],
                       check=True, capture_output=True, timeout=10)
        return path

    def plan_now(self):
        output = io.StringIO()
        with contextlib.redirect_stderr(output):
            self.module.plan_legacy(self.paths, self.plan)
        return output.getvalue()

    def test_known_crlf_bytes_are_planned_but_not_written(self):
        path = self.put('hooks/user-prompt.ps1', PROMPT.replace(b'\n', b'\r\n'), 0o755)
        before = read(path)
        self.plan_now()
        self.assertEqual(self.plan['legacy/hooks/user-prompt.ps1'], (None, before[1]))
        self.assertEqual(self.plan.expected['legacy/hooks/user-prompt.ps1'], before)
        self.assertEqual(read(path), before)
        self.assertFalse(self.paths.backups.exists())

    def test_modified_and_marker_only_files_are_preserved_with_warning(self):
        for data in (PROMPT + b'# user addition\n', b'# conductor gate\nexit 0\n', b''):
            with self.subTest(data=data):
                self.plan = Plan()
                path = self.put('hooks/user-prompt.ps1', data)
                warning = self.plan_now()
                self.assertNotIn('legacy/hooks/user-prompt.ps1', self.plan)
                self.assertEqual(path.read_bytes(), data)
                self.assertIn('WARNING', warning)
                self.assertIn('user-prompt.ps1', warning)

    def test_unknown_names_and_directories_are_preserved_with_warning(self):
        unknown = self.put('git-hooks/custom', POST_MERGE)
        self.put('hooks/custom.ps1', PROMPT)
        directory = self.paths.runtime / 'adapters/cursor/gate.ps1'
        directory.mkdir(parents=True)
        warning = self.plan_now()
        self.assertEqual(self.plan, {})
        self.assertTrue(directory.is_dir())
        self.assertEqual(unknown.read_bytes(), POST_MERGE)
        self.assertIn('custom', warning)
        self.assertIn('gate.ps1', warning)

    def test_absent_legacy_does_not_guess_ownership_from_state(self):
        self.put('install-state.json', b'{"legacy": true}')
        self.put('hooks/session-start.sh', b'current hook\n')
        self.assertEqual(self.plan_now(), '')
        self.assertEqual(self.plan, {})

    def test_global_config_planned_from_exact_origin_with_bytes_and_mode(self):
        for key in ('gitconfig', 'gitconfig-xdg'):
            with self.subTest(key=key):
                path = self.config(key)
                path.chmod(0o640)
                before = read(path)
                self.plan_now()
                after, mode = self.plan[key]
                self.assertNotIn(b'templateDir', after)
                self.assertIn(b'# personal comment\n', after)
                self.assertIn(b'Private Name', after)
                self.assertEqual(mode, before[1])
                self.assertEqual(self.plan.expected[key], before)
                self.assertEqual(read(path), before)
                path.unlink()
                self.plan = Plan()

    def test_similar_relative_tilde_and_foreign_values_are_preserved(self):
        for value in (str(self.paths.runtime / 'git-template') + '-foreign',
                      '~/.claude/conductor/git-template', '.claude/conductor/git-template',
                      str(self.root / 'foreign-template')):
            with self.subTest(value=value):
                path = self.config(value=value)
                before = read(path)
                warning = self.plan_now()
                self.assertNotIn('gitconfig', self.plan)
                self.assertEqual(read(path), before)
                self.assertIn('WARNING', warning)

    def test_mixed_template_keeps_registration_and_foreign_content(self):
        path = self.config()
        known = self.put('git-template/hooks/post-merge', POST_MERGE, 0o755)
        foreign = self.put('git-template/hooks/post-merge.pre-conductor', b'personal hook\n')
        before = read(path)
        warning = self.plan_now()
        self.assertNotIn('gitconfig', self.plan)
        self.assertIn('legacy/git-template/hooks/post-merge', self.plan)
        self.assertEqual(read(path), before)
        self.assertTrue(known.exists())
        self.assertEqual(foreign.read_bytes(), b'personal hook\n')
        self.assertIn('WARNING', warning)
        self.assertIn('post-merge.pre-conductor', warning)

    def test_known_template_cleanup_roundtrip_restores_bytes_and_modes(self):
        config = self.config()
        hook = self.put('git-template/hooks/post-merge', POST_MERGE, 0o755)
        before = {path: read(path) for path in (config, hook)}
        self.plan_now()
        backup = Transaction(self.paths, self.plan, self.plan.expected).apply(lambda: None)
        self.assertFalse(hook.exists())
        self.assertTrue(hook.parent.is_dir())
        self.assertNotIn(b'templateDir', config.read_bytes())
        rollback(self.paths, backup)
        self.assertEqual({path: read(path) for path in before}, before)

    def test_foreign_include_origin_is_preserved(self):
        included = self.root / 'included.cfg'
        target = (self.paths.runtime / 'git-template').as_posix()
        included.write_text('[init]\n\ttemplateDir = "' + target + '"\n', encoding='utf-8')
        config = self.paths.target('gitconfig')
        config.write_text('[include]\n\tpath = "' + included.as_posix() + '"\n', encoding='utf-8')
        before = {path: read(path) for path in (config, included)}
        warning = self.plan_now()
        self.assertNotIn('gitconfig', self.plan)
        self.assertEqual({path: read(path) for path in before}, before)
        self.assertIn('WARNING', warning)

    def test_git_environment_cannot_redirect_writes_or_trace(self):
        config = self.config()
        outside = self.root / 'outside.cfg'
        outside.write_bytes(config.read_bytes())
        trace = self.root / 'must-not-write.trace'
        with patch.dict(os.environ, {'GIT_CONFIG_GLOBAL': str(outside),
                                    'GIT_TRACE': str(trace), 'GIT_TRACE2_EVENT': str(trace)}):
            warning = self.plan_now()
        self.assertEqual(self.plan, {})
        self.assertIn('WARNING', warning)
        self.assertEqual(outside.read_bytes(), config.read_bytes())
        self.assertFalse(trace.exists())

    def test_git_overrides_do_not_affect_temporary_render_or_live_config(self):
        config = self.config()
        outside = self.root / 'outside.cfg'
        outside.write_bytes(b'[user]\nname = Outside\n')
        before = read(config)
        with patch.dict(os.environ, {'GIT_CONFIG_GLOBAL': str(config), 'GIT_CONFIG': str(outside),
                                    'GIT_CONFIG_COUNT': '1', 'GIT_CONFIG_KEY_0': 'init.templateDir',
                                    'GIT_CONFIG_VALUE_0': str(outside),
                                    'GIT_CONFIG_PARAMETERS': "'init.templateDir=foreign'"}):
            self.plan_now()
        self.assertIn('gitconfig', self.plan)
        self.assertEqual(read(config), before)
        self.assertEqual(outside.read_bytes(), b'[user]\nname = Outside\n')

    def test_duplicate_mixed_values_are_preserved(self):
        config = self.config()
        with config.open('ab') as stream:
            stream.write(b'\ttemplateDir = /foreign\n')
        before = read(config)
        warning = self.plan_now()
        self.assertNotIn('gitconfig', self.plan)
        self.assertEqual(read(config), before)
        self.assertIn('WARNING', warning)

    def test_malformed_git_config_is_preserved_with_warning(self):
        config = self.paths.target('gitconfig')
        config.write_bytes(b'[broken\n')
        warning = self.plan_now()
        self.assertEqual(self.plan, {})
        self.assertEqual(config.read_bytes(), b'[broken\n')
        self.assertIn('WARNING', warning)

    def test_concurrent_edit_after_plan_blocks_transaction(self):
        path = self.put('hooks/user-prompt.ps1', PROMPT)
        self.plan_now()
        path.write_bytes(PROMPT + b'# changed after planning\n')
        with self.assertRaisesRegex(ValueError, 'changed'):
            Transaction(self.paths, self.plan, self.plan.expected).apply(lambda: None)
        self.assertEqual(path.read_bytes(), PROMPT + b'# changed after planning\n')

    @unittest.skipIf(os.name == 'nt', 'POSIX symlink fixture')
    def test_links_never_authorize_deletion_or_config_rewrite(self):
        external = self.root / 'external'
        external.write_bytes(PROMPT)
        hook = self.paths.runtime / 'hooks/user-prompt.ps1'
        hook.parent.mkdir()
        hook.symlink_to(external)
        config = self.paths.target('gitconfig')
        config.symlink_to(external)
        warning = self.plan_now()
        self.assertEqual(self.plan, {})
        self.assertTrue(hook.is_symlink())
        self.assertEqual(external.read_bytes(), PROMPT)
        self.assertIn('WARNING', warning)


if __name__ == '__main__':
    unittest.main()
